/*
 * IBM Guardium Data Security Center
 * Use Guardium Data Security Center SDK (application programming interfaces) to interact with other applications, such as Guardium Data Protection, universal connectors, and Guardium Data Security Center reports.
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ibm.gdsc.sdk.models;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Status of connection.
 */
@JsonAdapter(Connectionsv3Status.Adapter.class)
public enum Connectionsv3Status {
  
  UNDEFINED_STATUS("UNDEFINED_STATUS"),
  
  STATUS_HEALTHY("STATUS_HEALTHY"),
  
  STATUS_UNHEALTHY("STATUS_UNHEALTHY"),
  
  STATUS_DISABLED("STATUS_DISABLED"),
  
  STATUS_INITIALIZING("STATUS_INITIALIZING");

  private String value;

  Connectionsv3Status(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static Connectionsv3Status fromValue(String value) {
    for (Connectionsv3Status b : Connectionsv3Status.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<Connectionsv3Status> {
    @Override
    public void write(final JsonWriter jsonWriter, final Connectionsv3Status enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public Connectionsv3Status read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return Connectionsv3Status.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    Connectionsv3Status.fromValue(value);
  }
}

