/*
 * IBM Guardium Data Security Center
 * IBM Guardium Data Security Center simplifies your organization's Data Security architecture and enables access to long-term data security and compliance data. It provides security teams with risk-based views and alerts, as well as advanced analytics based on proprietary ML technology to uncover hidden threats. IBM Guardium Data Security Center gives security professionals the ability to quickly create data security and audit reports, monitor activity in on-prem and DBaaS sources, and take action from a central location.
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.Authenticate400Response;
import java.math.BigDecimal;
import org.openapitools.client.model.DataResource;
import org.openapitools.client.model.DataResourcesSummary;
import org.openapitools.client.model.ListDataResources200Response;
import org.openapitools.client.model.ListDataResourcesFilterParameter;
import org.openapitools.client.model.ListDataResourcesSortParameter;
import org.openapitools.client.model.RemoveResource200Response;
import org.openapitools.client.model.UpdateResourceReviewBody;
import org.openapitools.client.model.UpdateResourceReviewStatus200Response;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DataResourcesApi
 */
@Disabled
public class DataResourcesApiTest {

    private final DataResourcesApi api = new DataResourcesApi();

    /**
     * Get a specific data resource by its ID
     *
     * Get additional details on a specific data resource by providing its ID.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getDataResourceTest() throws ApiException {
        String dataResourceId = null;
        DataResource response = api.getDataResource(dataResourceId);
        // TODO: test validations
    }

    /**
     * Data resources summary
     *
     * Get a summary of all the data resource, that is, number of data resources, types of data resources, and other information.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getDataResourcesSummaryTest() throws ApiException {
        String dataStoreId = null;
        ListDataResourcesFilterParameter filter = null;
        DataResourcesSummary response = api.getDataResourcesSummary(dataStoreId, filter);
        // TODO: test validations
    }

    /**
     * List data resources that match a given filter
     *
     * Get a list of data resources based on the filter applied. You can filter by data store ID, data resource ID, data resource name, and more.&lt;BR&gt;&lt;B&gt;Note:&lt;/B&gt; Filter needs to be HTML encoded.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listDataResourcesTest() throws ApiException {
        String dataStoreId = null;
        ListDataResourcesFilterParameter filter = null;
        ListDataResourcesSortParameter sort = null;
        BigDecimal pageSize = null;
        String nextToken = null;
        ListDataResources200Response response = api.listDataResources(dataStoreId, filter, sort, pageSize, nextToken);
        // TODO: test validations
    }

    /**
     * List names of data resources
     *
     * List and filter data resources by their names
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listDataResourcesNamesTest() throws ApiException {
        String prefix = null;
        String dataStoreId = null;
        List<String> response = api.listDataResourcesNames(prefix, dataStoreId);
        // TODO: test validations
    }

    /**
     * Remove resource from Guardium Insights SaaS DSPM
     *
     * Removes a resource, with all its sensitivities, from Guardium Insights SaaS DSPM dashboard. This action does not remove the resource from the resource&#39;s source environment.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void removeResourceTest() throws ApiException {
        String dataResourceId = null;
        String dataStoreId = null;
        RemoveResource200Response response = api.removeResource(dataResourceId, dataStoreId);
        // TODO: test validations
    }

    /**
     * Set review status of a data resource
     *
     * Set the review status of a specific data resource in a specific data store.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateResourceReviewStatusTest() throws ApiException {
        String dataResourceId = null;
        UpdateResourceReviewBody updateResourceReviewBody = null;
        UpdateResourceReviewStatus200Response response = api.updateResourceReviewStatus(dataResourceId, updateResourceReviewBody);
        // TODO: test validations
    }

}
