/*
 * IBM Guardium Data Security Center
 * Use Guardium Data Security Center SDK (application programming interfaces) to interact with other applications, such as Guardium Data Protection, universal connectors, and Guardium Data Security Center reports.
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ibm.gdsc.sdk.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.ibm.gdsc.sdk.models.Schedulerv3Frequency;
import com.ibm.gdsc.sdk.models.Schedulerv3Recipient;
import com.ibm.gdsc.sdk.models.Schedulerv3ScheduledTaskSummary;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Schedulerv3ScheduledJobSummary
 */
public class Schedulerv3ScheduledJobSummaryTest {
    private final Schedulerv3ScheduledJobSummary model = new Schedulerv3ScheduledJobSummary();

    /**
     * Model tests for Schedulerv3ScheduledJobSummary
     */
    @Test
    public void testSchedulerv3ScheduledJobSummary() {
        // TODO: test Schedulerv3ScheduledJobSummary
    }

    /**
     * Test the property 'creationTime'
     */
    @Test
    public void creationTimeTest() {
        // TODO: test creationTime
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'enabled'
     */
    @Test
    public void enabledTest() {
        // TODO: test enabled
    }

    /**
     * Test the property 'expired'
     */
    @Test
    public void expiredTest() {
        // TODO: test expired
    }

    /**
     * Test the property 'frequency'
     */
    @Test
    public void frequencyTest() {
        // TODO: test frequency
    }

    /**
     * Test the property 'lastModifiedTime'
     */
    @Test
    public void lastModifiedTimeTest() {
        // TODO: test lastModifiedTime
    }

    /**
     * Test the property 'lastRunDuration'
     */
    @Test
    public void lastRunDurationTest() {
        // TODO: test lastRunDuration
    }

    /**
     * Test the property 'lastRunStart'
     */
    @Test
    public void lastRunStartTest() {
        // TODO: test lastRunStart
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'nextRun'
     */
    @Test
    public void nextRunTest() {
        // TODO: test nextRun
    }

    /**
     * Test the property 'recipient'
     */
    @Test
    public void recipientTest() {
        // TODO: test recipient
    }

    /**
     * Test the property 'recipients'
     */
    @Test
    public void recipientsTest() {
        // TODO: test recipients
    }

    /**
     * Test the property 'reportNames'
     */
    @Test
    public void reportNamesTest() {
        // TODO: test reportNames
    }

    /**
     * Test the property 'scheduleId'
     */
    @Test
    public void scheduleIdTest() {
        // TODO: test scheduleId
    }

    /**
     * Test the property 'tags'
     */
    @Test
    public void tagsTest() {
        // TODO: test tags
    }

    /**
     * Test the property 'tasks'
     */
    @Test
    public void tasksTest() {
        // TODO: test tasks
    }

}
