/*
 * IBM Guardium Data Security Center
 * Use Guardium Data Security Center SDK (application programming interfaces) to interact with other applications, such as Guardium Data Protection, universal connectors, and Guardium Data Security Center reports.
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ibm.gdsc.sdk.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.ibm.gdsc.sdk.models.Edgeschedulerv3MonitoringPendingRequestForEdgeQueryResponse;
import com.ibm.gdsc.sdk.models.RuntimeStreamError;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for StreamResultOfEdgeschedulerv3MonitoringPendingRequestForEdgeQueryResponse
 */
public class StreamResultOfEdgeschedulerv3MonitoringPendingRequestForEdgeQueryResponseTest {
    private final StreamResultOfEdgeschedulerv3MonitoringPendingRequestForEdgeQueryResponse model = new StreamResultOfEdgeschedulerv3MonitoringPendingRequestForEdgeQueryResponse();

    /**
     * Model tests for StreamResultOfEdgeschedulerv3MonitoringPendingRequestForEdgeQueryResponse
     */
    @Test
    public void testStreamResultOfEdgeschedulerv3MonitoringPendingRequestForEdgeQueryResponse() {
        // TODO: test StreamResultOfEdgeschedulerv3MonitoringPendingRequestForEdgeQueryResponse
    }

    /**
     * Test the property 'error'
     */
    @Test
    public void errorTest() {
        // TODO: test error
    }

    /**
     * Test the property 'result'
     */
    @Test
    public void resultTest() {
        // TODO: test result
    }

}
