/*
 * IBM Guardium Data Security Center
 * Use Guardium Data Security Center SDK (application programming interfaces) to interact with other applications, such as Guardium Data Protection, universal connectors, and Guardium Data Security Center reports.
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ibm.gdsc.sdk.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.ibm.gdsc.sdk.models.GooglerpcStatus;
import com.ibm.gdsc.sdk.models.Workflowv3JobCount;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Workflowv3GetJobsCountResponse
 */
public class Workflowv3GetJobsCountResponseTest {
    private final Workflowv3GetJobsCountResponse model = new Workflowv3GetJobsCountResponse();

    /**
     * Model tests for Workflowv3GetJobsCountResponse
     */
    @Test
    public void testWorkflowv3GetJobsCountResponse() {
        // TODO: test Workflowv3GetJobsCountResponse
    }

    /**
     * Test the property 'counts'
     */
    @Test
    public void countsTest() {
        // TODO: test counts
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

}
