/*
 * IBM Guardium Data Security Center
 * Use Guardium Data Security Center SDK (application programming interfaces) to interact with other applications, such as Guardium Data Protection, universal connectors, and Guardium Data Security Center reports.
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ibm.gdsc.sdk;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * - LEVEL_UNKNOWN: no info about risk/criticality involved  - LEVEL_NONE: no risk/criticality involed  - LEVEL_LOW: low risk/criticality involed  - LEVEL_MEDIUM: medium risk/criticality involed  - LEVEL_HIGH: high risk/criticality involed  - LEVEL_CRITICAL: critical risk/criticality involed
 */
@JsonAdapter(Assetsv3Level.Adapter.class)
public enum Assetsv3Level {
  
  UNKNOWN("LEVEL_UNKNOWN"),
  
  NONE("LEVEL_NONE"),
  
  LOW("LEVEL_LOW"),
  
  MEDIUM("LEVEL_MEDIUM"),
  
  HIGH("LEVEL_HIGH"),
  
  CRITICAL("LEVEL_CRITICAL");

  private String value;

  Assetsv3Level(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static Assetsv3Level fromValue(String value) {
    for (Assetsv3Level b : Assetsv3Level.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<Assetsv3Level> {
    @Override
    public void write(final JsonWriter jsonWriter, final Assetsv3Level enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public Assetsv3Level read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return Assetsv3Level.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    Assetsv3Level.fromValue(value);
  }
}

