/*
 * IBM Guardium Data Security Center
 * Use Guardium Data Security Center SDK (application programming interfaces) to interact with other applications, such as Guardium Data Protection, universal connectors, and Guardium Data Security Center reports.
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ibm.gdsc.sdk;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.ibm.gdsc.sdk.Reportsv3TimestampMapping;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.ibm.gdsc.JSON;

/**
 * Reportsv3CategoryDetail
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-02-18T18:23:51.166908Z[UTC]", comments = "Generator version: 7.6.0")
public class Reportsv3CategoryDetail {
  public static final String SERIALIZED_NAME_CATEGORY_DESCRIPTION = "category_description";
  @SerializedName(SERIALIZED_NAME_CATEGORY_DESCRIPTION)
  private String categoryDescription;

  public static final String SERIALIZED_NAME_CATEGORY_NAME = "category_name";
  @SerializedName(SERIALIZED_NAME_CATEGORY_NAME)
  private String categoryName;

  public static final String SERIALIZED_NAME_CATEGORY_TABLES = "category_tables";
  @SerializedName(SERIALIZED_NAME_CATEGORY_TABLES)
  private List<String> categoryTables = new ArrayList<>();

  public static final String SERIALIZED_NAME_TIMESTAMP_MAPPING = "timestamp_mapping";
  @SerializedName(SERIALIZED_NAME_TIMESTAMP_MAPPING)
  private List<Reportsv3TimestampMapping> timestampMapping = new ArrayList<>();

  public Reportsv3CategoryDetail() {
  }

  public Reportsv3CategoryDetail categoryDescription(String categoryDescription) {
    this.categoryDescription = categoryDescription;
    return this;
  }

   /**
   * The category description.
   * @return categoryDescription
  **/
  @javax.annotation.Nullable
  public String getCategoryDescription() {
    return categoryDescription;
  }

  public void setCategoryDescription(String categoryDescription) {
    this.categoryDescription = categoryDescription;
  }


  public Reportsv3CategoryDetail categoryName(String categoryName) {
    this.categoryName = categoryName;
    return this;
  }

   /**
   * Identifies the NLS translated string.
   * @return categoryName
  **/
  @javax.annotation.Nullable
  public String getCategoryName() {
    return categoryName;
  }

  public void setCategoryName(String categoryName) {
    this.categoryName = categoryName;
  }


  public Reportsv3CategoryDetail categoryTables(List<String> categoryTables) {
    this.categoryTables = categoryTables;
    return this;
  }

  public Reportsv3CategoryDetail addCategoryTablesItem(String categoryTablesItem) {
    if (this.categoryTables == null) {
      this.categoryTables = new ArrayList<>();
    }
    this.categoryTables.add(categoryTablesItem);
    return this;
  }

   /**
   * Get categoryTables
   * @return categoryTables
  **/
  @javax.annotation.Nullable
  public List<String> getCategoryTables() {
    return categoryTables;
  }

  public void setCategoryTables(List<String> categoryTables) {
    this.categoryTables = categoryTables;
  }


  public Reportsv3CategoryDetail timestampMapping(List<Reportsv3TimestampMapping> timestampMapping) {
    this.timestampMapping = timestampMapping;
    return this;
  }

  public Reportsv3CategoryDetail addTimestampMappingItem(Reportsv3TimestampMapping timestampMappingItem) {
    if (this.timestampMapping == null) {
      this.timestampMapping = new ArrayList<>();
    }
    this.timestampMapping.add(timestampMappingItem);
    return this;
  }

   /**
   * Get timestampMapping
   * @return timestampMapping
  **/
  @javax.annotation.Nullable
  public List<Reportsv3TimestampMapping> getTimestampMapping() {
    return timestampMapping;
  }

  public void setTimestampMapping(List<Reportsv3TimestampMapping> timestampMapping) {
    this.timestampMapping = timestampMapping;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Reportsv3CategoryDetail reportsv3CategoryDetail = (Reportsv3CategoryDetail) o;
    return Objects.equals(this.categoryDescription, reportsv3CategoryDetail.categoryDescription) &&
        Objects.equals(this.categoryName, reportsv3CategoryDetail.categoryName) &&
        Objects.equals(this.categoryTables, reportsv3CategoryDetail.categoryTables) &&
        Objects.equals(this.timestampMapping, reportsv3CategoryDetail.timestampMapping);
  }

  @Override
  public int hashCode() {
    return Objects.hash(categoryDescription, categoryName, categoryTables, timestampMapping);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Reportsv3CategoryDetail {\n");
    sb.append("    categoryDescription: ").append(toIndentedString(categoryDescription)).append("\n");
    sb.append("    categoryName: ").append(toIndentedString(categoryName)).append("\n");
    sb.append("    categoryTables: ").append(toIndentedString(categoryTables)).append("\n");
    sb.append("    timestampMapping: ").append(toIndentedString(timestampMapping)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("category_description");
    openapiFields.add("category_name");
    openapiFields.add("category_tables");
    openapiFields.add("timestamp_mapping");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to Reportsv3CategoryDetail
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Reportsv3CategoryDetail.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in Reportsv3CategoryDetail is not found in the empty JSON string", Reportsv3CategoryDetail.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Reportsv3CategoryDetail.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `Reportsv3CategoryDetail` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("category_description") != null && !jsonObj.get("category_description").isJsonNull()) && !jsonObj.get("category_description").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `category_description` to be a primitive type in the JSON string but got `%s`", jsonObj.get("category_description").toString()));
      }
      if ((jsonObj.get("category_name") != null && !jsonObj.get("category_name").isJsonNull()) && !jsonObj.get("category_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `category_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("category_name").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("category_tables") != null && !jsonObj.get("category_tables").isJsonNull() && !jsonObj.get("category_tables").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `category_tables` to be an array in the JSON string but got `%s`", jsonObj.get("category_tables").toString()));
      }
      if (jsonObj.get("timestamp_mapping") != null && !jsonObj.get("timestamp_mapping").isJsonNull()) {
        JsonArray jsonArraytimestampMapping = jsonObj.getAsJsonArray("timestamp_mapping");
        if (jsonArraytimestampMapping != null) {
          // ensure the json data is an array
          if (!jsonObj.get("timestamp_mapping").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `timestamp_mapping` to be an array in the JSON string but got `%s`", jsonObj.get("timestamp_mapping").toString()));
          }

          // validate the optional field `timestamp_mapping` (array)
          for (int i = 0; i < jsonArraytimestampMapping.size(); i++) {
            Reportsv3TimestampMapping.validateJsonElement(jsonArraytimestampMapping.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Reportsv3CategoryDetail.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Reportsv3CategoryDetail' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Reportsv3CategoryDetail> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Reportsv3CategoryDetail.class));

       return (TypeAdapter<T>) new TypeAdapter<Reportsv3CategoryDetail>() {
           @Override
           public void write(JsonWriter out, Reportsv3CategoryDetail value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Reportsv3CategoryDetail read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of Reportsv3CategoryDetail given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of Reportsv3CategoryDetail
  * @throws IOException if the JSON string is invalid with respect to Reportsv3CategoryDetail
  */
  public static Reportsv3CategoryDetail fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Reportsv3CategoryDetail.class);
  }

 /**
  * Convert an instance of Reportsv3CategoryDetail to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

