/*
IBM Guardium Data Security Center

Testing ThirdPartyVendorsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package guardiumsdkgo

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_guardiumsdkgo_ThirdPartyVendorsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ThirdPartyVendorsAPIService GetLinkedVendor", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var vendorId string

		resp, httpRes, err := apiClient.ThirdPartyVendorsAPI.GetLinkedVendor(context.Background(), vendorId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ThirdPartyVendorsAPIService GetSingleLinkedVendor", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var vendorId string

		resp, httpRes, err := apiClient.ThirdPartyVendorsAPI.GetSingleLinkedVendor(context.Background(), vendorId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ThirdPartyVendorsAPIService ListLinkedVendorDataStores", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var vendorId string

		resp, httpRes, err := apiClient.ThirdPartyVendorsAPI.ListLinkedVendorDataStores(context.Background(), vendorId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ThirdPartyVendorsAPIService ListLinkedVendors", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ThirdPartyVendorsAPI.ListLinkedVendors(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ThirdPartyVendorsAPIService ListTrustedAssets", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ThirdPartyVendorsAPI.ListTrustedAssets(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
