/*
 * IBM Guardium Data Security Center
 * IBM Guardium Data Security Center simplifies your organization's Data Security architecture and enables access to long-term data security and compliance data. It provides security teams with risk-based views and alerts, as well as advanced analytics based on proprietary ML technology to uncover hidden threats. IBM Guardium Data Security Center gives security professionals the ability to quickly create data security and audit reports, monitor activity in on-prem and DBaaS sources, and take action from a central location.
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ibm.gdsc.sdk;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.ibm.gdsc.sdk.Assetsv3ConnectionEdge;
import com.ibm.gdsc.sdk.Assetsv3CustomProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Assetsv3HostVertex
 */
public class Assetsv3HostVertexTest {
    private final Assetsv3HostVertex model = new Assetsv3HostVertex();

    /**
     * Model tests for Assetsv3HostVertex
     */
    @Test
    public void testAssetsv3HostVertex() {
        // TODO: test Assetsv3HostVertex
    }

    /**
     * Test the property 'city'
     */
    @Test
    public void cityTest() {
        // TODO: test city
    }

    /**
     * Test the property 'country'
     */
    @Test
    public void countryTest() {
        // TODO: test country
    }

    /**
     * Test the property 'dataCenter'
     */
    @Test
    public void dataCenterTest() {
        // TODO: test dataCenter
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'dns'
     */
    @Test
    public void dnsTest() {
        // TODO: test dns
    }

    /**
     * Test the property 'extendedProperties'
     */
    @Test
    public void extendedPropertiesTest() {
        // TODO: test extendedProperties
    }

    /**
     * Test the property 'hostIp'
     */
    @Test
    public void hostIpTest() {
        // TODO: test hostIp
    }

    /**
     * Test the property 'hostName'
     */
    @Test
    public void hostNameTest() {
        // TODO: test hostName
    }

    /**
     * Test the property 'hostPort'
     */
    @Test
    public void hostPortTest() {
        // TODO: test hostPort
    }

    /**
     * Test the property 'region'
     */
    @Test
    public void regionTest() {
        // TODO: test region
    }

    /**
     * Test the property 'resolutionKey'
     */
    @Test
    public void resolutionKeyTest() {
        // TODO: test resolutionKey
    }

    /**
     * Test the property 'state'
     */
    @Test
    public void stateTest() {
        // TODO: test state
    }

}
