/*
 * IBM Guardium Data Security Center
 * Use Guardium Data Security Center SDK (application programming interfaces) to interact with other applications, such as Guardium Data Protection, universal connectors, and Guardium Data Security Center reports.
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ibm.gdsc.sdk;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.ibm.gdsc.sdk.Schedulerv3DayOfWeek;
import com.ibm.gdsc.sdk.Schedulerv3DayOrder;
import com.ibm.gdsc.sdk.Schedulerv3Frequency;
import com.ibm.gdsc.sdk.Schedulerv3Month;
import com.ibm.gdsc.sdk.Schedulerv3RepeatBegin;
import com.ibm.gdsc.sdk.Schedulerv3RepeatEnd;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Complianceacceleratorv3AuditScheduler
 */
public class Complianceacceleratorv3AuditSchedulerTest {
    private final Complianceacceleratorv3AuditScheduler model = new Complianceacceleratorv3AuditScheduler();

    /**
     * Model tests for Complianceacceleratorv3AuditScheduler
     */
    @Test
    public void testComplianceacceleratorv3AuditScheduler() {
        // TODO: test Complianceacceleratorv3AuditScheduler
    }

    /**
     * Test the property 'beginSchedule'
     */
    @Test
    public void beginScheduleTest() {
        // TODO: test beginSchedule
    }

    /**
     * Test the property 'byDayOfMonth'
     */
    @Test
    public void byDayOfMonthTest() {
        // TODO: test byDayOfMonth
    }

    /**
     * Test the property 'dayOfMonth'
     */
    @Test
    public void dayOfMonthTest() {
        // TODO: test dayOfMonth
    }

    /**
     * Test the property 'dayOfWeek'
     */
    @Test
    public void dayOfWeekTest() {
        // TODO: test dayOfWeek
    }

    /**
     * Test the property 'dayOrder'
     */
    @Test
    public void dayOrderTest() {
        // TODO: test dayOrder
    }

    /**
     * Test the property 'dayOrderDayOfWeek'
     */
    @Test
    public void dayOrderDayOfWeekTest() {
        // TODO: test dayOrderDayOfWeek
    }

    /**
     * Test the property 'endSchedule'
     */
    @Test
    public void endScheduleTest() {
        // TODO: test endSchedule
    }

    /**
     * Test the property 'frequency'
     */
    @Test
    public void frequencyTest() {
        // TODO: test frequency
    }

    /**
     * Test the property 'months'
     */
    @Test
    public void monthsTest() {
        // TODO: test months
    }

    /**
     * Test the property 'neverEnd'
     */
    @Test
    public void neverEndTest() {
        // TODO: test neverEnd
    }

    /**
     * Test the property 'repeat'
     */
    @Test
    public void repeatTest() {
        // TODO: test repeat
    }

    /**
     * Test the property 'repeatBegin'
     */
    @Test
    public void repeatBeginTest() {
        // TODO: test repeatBegin
    }

    /**
     * Test the property 'repeatEnd'
     */
    @Test
    public void repeatEndTest() {
        // TODO: test repeatEnd
    }

}
