/*
 * IBM Guardium Data Security Center
 * IBM Guardium Data Security Center simplifies your organization's Data Security architecture and enables access to long-term data security and compliance data. It provides security teams with risk-based views and alerts, as well as advanced analytics based on proprietary ML technology to uncover hidden threats. IBM Guardium Data Security Center gives security professionals the ability to quickly create data security and audit reports, monitor activity in on-prem and DBaaS sources, and take action from a central location.
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ibm.gdsc.sdk;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.ibm.gdsc.sdk.Dashboardsv3Card;
import com.ibm.gdsc.sdk.Dashboardsv3ReportGlobalFilter;
import com.ibm.gdsc.sdk.Dashboardsv3TimeRange;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Dashboardsv3Dashboard
 */
public class Dashboardsv3DashboardTest {
    private final Dashboardsv3Dashboard model = new Dashboardsv3Dashboard();

    /**
     * Model tests for Dashboardsv3Dashboard
     */
    @Test
    public void testDashboardsv3Dashboard() {
        // TODO: test Dashboardsv3Dashboard
    }

    /**
     * Test the property 'cards'
     */
    @Test
    public void cardsTest() {
        // TODO: test cards
    }

    /**
     * Test the property 'dashboardDescription'
     */
    @Test
    public void dashboardDescriptionTest() {
        // TODO: test dashboardDescription
    }

    /**
     * Test the property 'dashboardId'
     */
    @Test
    public void dashboardIdTest() {
        // TODO: test dashboardId
    }

    /**
     * Test the property 'dashboardTitle'
     */
    @Test
    public void dashboardTitleTest() {
        // TODO: test dashboardTitle
    }

    /**
     * Test the property 'globalTimeFilter'
     */
    @Test
    public void globalTimeFilterTest() {
        // TODO: test globalTimeFilter
    }

    /**
     * Test the property 'reportGlobalFilterList'
     */
    @Test
    public void reportGlobalFilterListTest() {
        // TODO: test reportGlobalFilterList
    }

}
