/*
 * IBM Guardium Data Security Center
 * IBM Guardium Data Security Center simplifies your organization's Data Security architecture and enables access to long-term data security and compliance data. It provides security teams with risk-based views and alerts, as well as advanced analytics based on proprietary ML technology to uncover hidden threats. IBM Guardium Data Security Center gives security professionals the ability to quickly create data security and audit reports, monitor activity in on-prem and DBaaS sources, and take action from a central location.
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ibm.gdsc.sdk;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.ibm.gdsc.sdk.Groupbuilderv3Group;
import com.ibm.gdsc.sdk.Groupbuilderv3LdapConfig;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Groupbuilderv3ImportGroupRequest
 */
public class Groupbuilderv3ImportGroupRequestTest {
    private final Groupbuilderv3ImportGroupRequest model = new Groupbuilderv3ImportGroupRequest();

    /**
     * Model tests for Groupbuilderv3ImportGroupRequest
     */
    @Test
    public void testGroupbuilderv3ImportGroupRequest() {
        // TODO: test Groupbuilderv3ImportGroupRequest
    }

    /**
     * Test the property 'centralManagerId'
     */
    @Test
    public void centralManagerIdTest() {
        // TODO: test centralManagerId
    }

    /**
     * Test the property 'groups'
     */
    @Test
    public void groupsTest() {
        // TODO: test groups
    }

    /**
     * Test the property 'ldapConfig'
     */
    @Test
    public void ldapConfigTest() {
        // TODO: test ldapConfig
    }

    /**
     * Test the property 'oneTime'
     */
    @Test
    public void oneTimeTest() {
        // TODO: test oneTime
    }

    /**
     * Test the property 'preview'
     */
    @Test
    public void previewTest() {
        // TODO: test preview
    }

}
