/*
 * IBM Guardium Data Security Center
 * Use Guardium Data Security Center SDK (application programming interfaces) to interact with other applications, such as Guardium Data Protection, universal connectors, and Guardium Data Security Center reports.
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ibm.gdsc.sdk;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Guardiumconnectorv3InspectionEngineObject
 */
public class Guardiumconnectorv3InspectionEngineObjectTest {
    private final Guardiumconnectorv3InspectionEngineObject model = new Guardiumconnectorv3InspectionEngineObject();

    /**
     * Model tests for Guardiumconnectorv3InspectionEngineObject
     */
    @Test
    public void testGuardiumconnectorv3InspectionEngineObject() {
        // TODO: test Guardiumconnectorv3InspectionEngineObject
    }

    /**
     * Test the property 'ieStatus'
     */
    @Test
    public void ieStatusTest() {
        // TODO: test ieStatus
    }

    /**
     * Test the property 'inspectionEngine'
     */
    @Test
    public void inspectionEngineTest() {
        // TODO: test inspectionEngine
    }

}
