/*
 * IBM Guardium Data Security Center
 * IBM Guardium Data Security Center simplifies your organization's Data Security architecture and enables access to long-term data security and compliance data. It provides security teams with risk-based views and alerts, as well as advanced analytics based on proprietary ML technology to uncover hidden threats. IBM Guardium Data Security Center gives security professionals the ability to quickly create data security and audit reports, monitor activity in on-prem and DBaaS sources, and take action from a central location.
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ibm.gdsc.sdk;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Schedulerv3RepeatEnd
 */
public class Schedulerv3RepeatEndTest {
    private final Schedulerv3RepeatEnd model = new Schedulerv3RepeatEnd();

    /**
     * Model tests for Schedulerv3RepeatEnd
     */
    @Test
    public void testSchedulerv3RepeatEnd() {
        // TODO: test Schedulerv3RepeatEnd
    }

    /**
     * Test the property 'hour'
     */
    @Test
    public void hourTest() {
        // TODO: test hour
    }

    /**
     * Test the property 'minute'
     */
    @Test
    public void minuteTest() {
        // TODO: test minute
    }

    /**
     * Test the property 'timezone'
     */
    @Test
    public void timezoneTest() {
        // TODO: test timezone
    }

}
