/*
 * IBM Guardium Data Security Center
 * IBM Guardium Data Security Center simplifies your organization's Data Security architecture and enables access to long-term data security and compliance data. It provides security teams with risk-based views and alerts, as well as advanced analytics based on proprietary ML technology to uncover hidden threats. IBM Guardium Data Security Center gives security professionals the ability to quickly create data security and audit reports, monitor activity in on-prem and DBaaS sources, and take action from a central location.
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ibm.gdsc.sdk;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.ibm.gdsc.sdk.Compliance;
import com.ibm.gdsc.sdk.VulnerabilityAffectedDataStoreFilterOptions;
import com.ibm.gdsc.sdk.VulnerabilityCriticality;
import com.ibm.gdsc.sdk.VulnerabilityStatusType;
import com.ibm.gdsc.sdk.VulnerabilityStatusTypeFamily;
import com.ibm.gdsc.sdk.VulnerabilityThreatCategory;
import com.ibm.gdsc.sdk.VulnerabilityType;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for VulnerabilitiesByDataStoreFilterOptions
 */
public class VulnerabilitiesByDataStoreFilterOptionsTest {
    private final VulnerabilitiesByDataStoreFilterOptions model = new VulnerabilitiesByDataStoreFilterOptions();

    /**
     * Model tests for VulnerabilitiesByDataStoreFilterOptions
     */
    @Test
    public void testVulnerabilitiesByDataStoreFilterOptions() {
        // TODO: test VulnerabilitiesByDataStoreFilterOptions
    }

    /**
     * Test the property 'vulnerabilityTypes'
     */
    @Test
    public void vulnerabilityTypesTest() {
        // TODO: test vulnerabilityTypes
    }

    /**
     * Test the property 'criticalities'
     */
    @Test
    public void criticalitiesTest() {
        // TODO: test criticalities
    }

    /**
     * Test the property 'threats'
     */
    @Test
    public void threatsTest() {
        // TODO: test threats
    }

    /**
     * Test the property 'compliance'
     */
    @Test
    public void complianceTest() {
        // TODO: test compliance
    }

    /**
     * Test the property 'threatCategories'
     */
    @Test
    public void threatCategoriesTest() {
        // TODO: test threatCategories
    }

    /**
     * Test the property 'affectedDataStore'
     */
    @Test
    public void affectedDataStoreTest() {
        // TODO: test affectedDataStore
    }

    /**
     * Test the property 'statusTypes'
     */
    @Test
    public void statusTypesTest() {
        // TODO: test statusTypes
    }

    /**
     * Test the property 'statusTypeFamilies'
     */
    @Test
    public void statusTypeFamiliesTest() {
        // TODO: test statusTypeFamilies
    }

    /**
     * Test the property 'discoveredSince'
     */
    @Test
    public void discoveredSinceTest() {
        // TODO: test discoveredSince
    }

    /**
     * Test the property 'sensitiveTags'
     */
    @Test
    public void sensitiveTagsTest() {
        // TODO: test sensitiveTags
    }

    /**
     * Test the property 'compliances'
     */
    @Test
    public void compliancesTest() {
        // TODO: test compliances
    }

}
