/*
 * IBM Guardium Data Security Center
 * IBM Guardium Data Security Center simplifies your organization's Data Security architecture and enables access to long-term data security and compliance data. It provides security teams with risk-based views and alerts, as well as advanced analytics based on proprietary ML technology to uncover hidden threats. IBM Guardium Data Security Center gives security professionals the ability to quickly create data security and audit reports, monitor activity in on-prem and DBaaS sources, and take action from a central location.
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ibm.gdsc.sdk;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.ibm.gdsc.sdk.Workflowv3OperatorType;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Workflowv3FilterColumn
 */
public class Workflowv3FilterColumnTest {
    private final Workflowv3FilterColumn model = new Workflowv3FilterColumn();

    /**
     * Model tests for Workflowv3FilterColumn
     */
    @Test
    public void testWorkflowv3FilterColumn() {
        // TODO: test Workflowv3FilterColumn
    }

    /**
     * Test the property 'headerName'
     */
    @Test
    public void headerNameTest() {
        // TODO: test headerName
    }

    /**
     * Test the property 'operatorType'
     */
    @Test
    public void operatorTypeTest() {
        // TODO: test operatorType
    }

    /**
     * Test the property 'values'
     */
    @Test
    public void valuesTest() {
        // TODO: test values
    }

}
