/**
 * IBM Guardium Data Security Center
 * Use Guardium Data Security Center SDK (application programming interfaces) to interact with other applications, such as Guardium Data Protection, universal connectors, and Guardium Data Security Center reports.
 *
 * OpenAPI spec version: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AnalyzedRegionValidationResults } from '../models/AnalyzedRegionValidationResults';
import { HttpFile } from '../http/http';

export class AddAnalyzedRegion200Response {
    'url'?: string;
    'userData'?: string;
    'imageId'?: string;
    'subnetId'?: string;
    'vpcId'?: string;
    'availabilityZone'?: string;
    'installationScript'?: string;
    'validationResults'?: AnalyzedRegionValidationResults;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "url",
            "baseName": "url",
            "type": "string",
            "format": ""
        },
        {
            "name": "userData",
            "baseName": "userData",
            "type": "string",
            "format": ""
        },
        {
            "name": "imageId",
            "baseName": "imageId",
            "type": "string",
            "format": ""
        },
        {
            "name": "subnetId",
            "baseName": "subnetId",
            "type": "string",
            "format": ""
        },
        {
            "name": "vpcId",
            "baseName": "vpcId",
            "type": "string",
            "format": ""
        },
        {
            "name": "availabilityZone",
            "baseName": "availabilityZone",
            "type": "string",
            "format": ""
        },
        {
            "name": "installationScript",
            "baseName": "installationScript",
            "type": "string",
            "format": ""
        },
        {
            "name": "validationResults",
            "baseName": "validationResults",
            "type": "AnalyzedRegionValidationResults",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AddAnalyzedRegion200Response.attributeTypeMap;
    }

    public constructor() {
    }
}
