/**
 * IBM Guardium Data Security Center
 * Use Guardium Data Security Center SDK (application programming interfaces) to interact with other applications, such as Guardium Data Protection, universal connectors, and Guardium Data Security Center reports.
 *
 * OpenAPI spec version: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CloudAccountCountInner } from '../models/CloudAccountCountInner';
import { CloudRegionCountInner } from '../models/CloudRegionCountInner';
import { TypesCountInner } from '../models/TypesCountInner';
import { HttpFile } from '../http/http';

export class FlowNodeSummary {
    'typesCount': Array<TypesCountInner>;
    'cloudAccountsCount': Array<CloudAccountCountInner>;
    'cloudRegionsCount': Array<CloudRegionCountInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "typesCount",
            "baseName": "typesCount",
            "type": "Array<TypesCountInner>",
            "format": ""
        },
        {
            "name": "cloudAccountsCount",
            "baseName": "cloudAccountsCount",
            "type": "Array<CloudAccountCountInner>",
            "format": ""
        },
        {
            "name": "cloudRegionsCount",
            "baseName": "cloudRegionsCount",
            "type": "Array<CloudRegionCountInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return FlowNodeSummary.attributeTypeMap;
    }

    public constructor() {
    }
}
