/**
 * IBM Guardium Data Security Center
 * IBM Guardium Data Security Center simplifies your organization\'s Data Security architecture and enables access to long-term data security and compliance data. It provides security teams with risk-based views and alerts, as well as advanced analytics based on proprietary ML technology to uncover hidden threats. IBM Guardium Data Security Center gives security professionals the ability to quickly create data security and audit reports, monitor activity in on-prem and DBaaS sources, and take action from a central location.
 *
 * OpenAPI spec version: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Guardiumconnectorv3MUDetailsObj } from '../models/Guardiumconnectorv3MUDetailsObj';
import { HttpFile } from '../http/http';

/**
* Information about managed units.
*/
export class Guardiumconnectorv3ManagedUnitObject {
    /**
    * Aggregation health status.
    */
    'aggHealthStatus'?: number;
    /**
    * Connectivity status.
    */
    'connectivity'?: number;
    'details'?: Guardiumconnectorv3MUDetailsObj;
    /**
    * Aggregator the Managed Unit exports data to.
    */
    'exportsTo'?: Array<string>;
    /**
    * ID.
    */
    'id'?: number;
    /**
    * Managed Units the aggregator imports data from.
    */
    'importsFrom'?: Array<string>;
    /**
    * Monitoring agent health status.
    */
    'musStapsHealthStatus'?: number;
    /**
    * Operating system version.
    */
    'osVersion'?: string;
    /**
    * Patch number.
    */
    'patch'?: string;
    /**
    * Overall status.
    */
    'status'?: number;
    /**
    * Unit type.
    */
    'type'?: string;
    /**
    * Name of the Guardium Data Protection system.
    */
    'unitHostname'?: string;
    /**
    * IP address.
    */
    'unitIp'?: string;
    /**
    * Unit utilization status.
    */
    'unitUtilizationHealthStatus'?: number;
    /**
    * Guardium Data Protection version.
    */
    'version'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "aggHealthStatus",
            "baseName": "agg_health_status",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "connectivity",
            "baseName": "connectivity",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "details",
            "baseName": "details",
            "type": "Guardiumconnectorv3MUDetailsObj",
            "format": ""
        },
        {
            "name": "exportsTo",
            "baseName": "exports_to",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "importsFrom",
            "baseName": "imports_from",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "musStapsHealthStatus",
            "baseName": "mus_staps_health_status",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "osVersion",
            "baseName": "os_version",
            "type": "string",
            "format": ""
        },
        {
            "name": "patch",
            "baseName": "patch",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        },
        {
            "name": "unitHostname",
            "baseName": "unit_hostname",
            "type": "string",
            "format": ""
        },
        {
            "name": "unitIp",
            "baseName": "unit_ip",
            "type": "string",
            "format": ""
        },
        {
            "name": "unitUtilizationHealthStatus",
            "baseName": "unit_utilization_health_status",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "version",
            "baseName": "version",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Guardiumconnectorv3ManagedUnitObject.attributeTypeMap;
    }

    public constructor() {
    }
}

