/**
 * IBM Guardium Data Security Center
 * Use Guardium Data Security Center SDK (application programming interfaces) to interact with other applications, such as Guardium Data Protection, universal connectors, and Guardium Data Security Center reports.
 *
 * OpenAPI spec version: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Healthcollectorv3AggregationDetailsObject } from '../models/Healthcollectorv3AggregationDetailsObject';
import { Healthcollectorv3GeneralDetailsObject } from '../models/Healthcollectorv3GeneralDetailsObject';
import { Healthcollectorv3UtilizationParameterObject } from '../models/Healthcollectorv3UtilizationParameterObject';
import { HttpFile } from '../http/http';

/**
* MUDetailObj gets additional information about managed units.
*/
export class Healthcollectorv3MUDetailsObj {
    /**
    * Aggregation details.
    */
    'aggregationDetailsList'?: Array<Healthcollectorv3AggregationDetailsObject>;
    'connectivityDetails'?: Healthcollectorv3GeneralDetailsObject;
    /**
    * Additional messages and details about managed units.
    */
    'generalErrMessages'?: Array<string>;
    'utilizationParametersValues'?: Healthcollectorv3UtilizationParameterObject;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "aggregationDetailsList",
            "baseName": "aggregation_details_list",
            "type": "Array<Healthcollectorv3AggregationDetailsObject>",
            "format": ""
        },
        {
            "name": "connectivityDetails",
            "baseName": "connectivity_details",
            "type": "Healthcollectorv3GeneralDetailsObject",
            "format": ""
        },
        {
            "name": "generalErrMessages",
            "baseName": "general_err_messages",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "utilizationParametersValues",
            "baseName": "utilization_parameters_values",
            "type": "Healthcollectorv3UtilizationParameterObject",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Healthcollectorv3MUDetailsObj.attributeTypeMap;
    }

    public constructor() {
    }
}
