/**
 * IBM Guardium Data Security Center
 * IBM Guardium Data Security Center simplifies your organization\'s Data Security architecture and enables access to long-term data security and compliance data. It provides security teams with risk-based views and alerts, as well as advanced analytics based on proprietary ML technology to uncover hidden threats. IBM Guardium Data Security Center gives security professionals the ability to quickly create data security and audit reports, monitor activity in on-prem and DBaaS sources, and take action from a central location.
 *
 * OpenAPI spec version: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Tenantuserv3ExternalMetadata } from '../models/Tenantuserv3ExternalMetadata';
import { HttpFile } from '../http/http';

/**
* UpdateTenantRequest message for PUT v3/tenants/{tenant_id} api.
*/
export class Jumpboxv3UpdateTenantRequest {
    /**
    * External metadata.
    */
    'externalMetadata'?: { [key: string]: Tenantuserv3ExternalMetadata; };
    /**
    * Is inactive.
    */
    'isInactive'?: boolean;
    /**
    * Is ready.
    */
    'isReady'?: boolean;
    /**
    * Name.
    */
    'name'?: string;
    /**
    * Part number.
    */
    'partNumber'?: string;
    /**
    * Tenant id.
    */
    'tenantId'?: string;
    /**
    * Email.
    */
    'uid'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "externalMetadata",
            "baseName": "external_metadata",
            "type": "{ [key: string]: Tenantuserv3ExternalMetadata; }",
            "format": ""
        },
        {
            "name": "isInactive",
            "baseName": "is_inactive",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isReady",
            "baseName": "is_ready",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "partNumber",
            "baseName": "part_number",
            "type": "string",
            "format": ""
        },
        {
            "name": "tenantId",
            "baseName": "tenant_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "uid",
            "baseName": "uid",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Jumpboxv3UpdateTenantRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

