/**
 * IBM Guardium Data Security Center
 * Use Guardium Data Security Center SDK (application programming interfaces) to interact with other applications, such as Guardium Data Protection, universal connectors, and Guardium Data Security Center reports.
 *
 * OpenAPI spec version: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Action parameter metadata object.
*/
export class Policybuilderv3ActionParameterMetadata {
    /**
    * Default value of the parameter.
    */
    'defaultValue'?: string;
    /**
    * Flag indicating if the parameter is manadatory or not.
    */
    'mandatory'?: boolean;
    /**
    * Name of the parameter.
    */
    'name'?: string;
    /**
    * Possible values of the parameter.
    */
    'possibleValues'?: Array<string>;
    /**
    * Sequence of the parameter.
    */
    'sequence'?: number;
    /**
    * TYpe of the Parameter like String, Number, Reg and so on.
    */
    'type'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "defaultValue",
            "baseName": "default_value",
            "type": "string",
            "format": ""
        },
        {
            "name": "mandatory",
            "baseName": "mandatory",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "possibleValues",
            "baseName": "possible_values",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "sequence",
            "baseName": "sequence",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Policybuilderv3ActionParameterMetadata.attributeTypeMap;
    }

    public constructor() {
    }
}

