/**
 * IBM Guardium Data Security Center
 * Use Guardium Data Security Center SDK (application programming interfaces) to interact with other applications, such as Guardium Data Protection, universal connectors, and Guardium Data Security Center reports.
 *
 * OpenAPI spec version: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AccessType } from '../models/AccessType';
import { FlowNode } from '../models/FlowNode';
import { HttpFile } from '../http/http';

export class PotentialFlowListItem {
    'id': string;
    'type': string;
    'source': FlowNode;
    'destination': FlowNode;
    'accessTypes': Array<AccessType>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        },
        {
            "name": "source",
            "baseName": "source",
            "type": "FlowNode",
            "format": ""
        },
        {
            "name": "destination",
            "baseName": "destination",
            "type": "FlowNode",
            "format": ""
        },
        {
            "name": "accessTypes",
            "baseName": "accessTypes",
            "type": "Array<AccessType>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PotentialFlowListItem.attributeTypeMap;
    }

    public constructor() {
    }
}

