/**
 * IBM Guardium Data Security Center
 * Use Guardium Data Security Center SDK (application programming interfaces) to interact with other applications, such as Guardium Data Protection, universal connectors, and Guardium Data Security Center reports.
 *
 * OpenAPI spec version: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class Qsdataloaderv3QSfileValidatorExternalParamRequest {
    'applicationFileName'?: string;
    'bucketName'?: string;
    'explorerFileName'?: string;
    'folderName'?: string;
    'networkFileName'?: string;
    'policyFileName'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "applicationFileName",
            "baseName": "application_file_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "bucketName",
            "baseName": "bucket_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "explorerFileName",
            "baseName": "explorer_file_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "folderName",
            "baseName": "folder_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "networkFileName",
            "baseName": "network_file_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "policyFileName",
            "baseName": "policy_file_name",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Qsdataloaderv3QSfileValidatorExternalParamRequest.attributeTypeMap;
    }

    public constructor() {
    }
}
