/**
 * IBM Guardium Data Security Center
 * Use Guardium Data Security Center SDK (application programming interfaces) to interact with other applications, such as Guardium Data Protection, universal connectors, and Guardium Data Security Center reports.
 *
 * OpenAPI spec version: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Reportsv3AggregationType } from '../models/Reportsv3AggregationType';
import { Reportsv3FieldName } from '../models/Reportsv3FieldName';
import { Reportsv3HeaderDataType } from '../models/Reportsv3HeaderDataType';
import { Reportsv3HeaderDescription } from '../models/Reportsv3HeaderDescription';
import { Reportsv3HeaderType } from '../models/Reportsv3HeaderType';
import { Reportsv3Literal } from '../models/Reportsv3Literal';
import { Reportsv3OrderBy } from '../models/Reportsv3OrderBy';
import { HttpFile } from '../http/http';

/**
* Report header.
*/
export class Reportsv3ReportHeader {
    'aggregationType'?: Reportsv3AggregationType;
    'fieldName'?: Reportsv3FieldName;
    /**
    * Group type id for the filter.
    */
    'groupTypeId'?: number;
    'headerDataType'?: Reportsv3HeaderDataType;
    'headerDescription'?: Reportsv3HeaderDescription;
    /**
    * Header ID.
    */
    'headerId'?: string;
    /**
    * The header name.
    */
    'headerName'?: string;
    'headerType'?: Reportsv3HeaderType;
    /**
    * Header type length.
    */
    'headerTypeLength'?: number;
    'literal'?: Reportsv3Literal;
    'orderBy'?: Reportsv3OrderBy;
    /**
    * Order by sequence.
    */
    'orderBySeq'?: number;
    /**
    * Schema name.
    */
    'schemaName'?: string;
    /**
    * Column sequence number.
    */
    'sequence'?: number;
    /**
    * Table name.
    */
    'tableName'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "aggregationType",
            "baseName": "aggregation_type",
            "type": "Reportsv3AggregationType",
            "format": ""
        },
        {
            "name": "fieldName",
            "baseName": "field_name",
            "type": "Reportsv3FieldName",
            "format": ""
        },
        {
            "name": "groupTypeId",
            "baseName": "group_type_id",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "headerDataType",
            "baseName": "header_data_type",
            "type": "Reportsv3HeaderDataType",
            "format": ""
        },
        {
            "name": "headerDescription",
            "baseName": "header_description",
            "type": "Reportsv3HeaderDescription",
            "format": ""
        },
        {
            "name": "headerId",
            "baseName": "header_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "headerName",
            "baseName": "header_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "headerType",
            "baseName": "header_type",
            "type": "Reportsv3HeaderType",
            "format": ""
        },
        {
            "name": "headerTypeLength",
            "baseName": "header_type_length",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "literal",
            "baseName": "literal",
            "type": "Reportsv3Literal",
            "format": ""
        },
        {
            "name": "orderBy",
            "baseName": "order_by",
            "type": "Reportsv3OrderBy",
            "format": ""
        },
        {
            "name": "orderBySeq",
            "baseName": "order_by_seq",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "schemaName",
            "baseName": "schema_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "sequence",
            "baseName": "sequence",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "tableName",
            "baseName": "table_name",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Reportsv3ReportHeader.attributeTypeMap;
    }

    public constructor() {
    }
}



