/**
 * IBM Guardium Data Security Center
 * Use Guardium Data Security Center SDK (application programming interfaces) to interact with other applications, such as Guardium Data Protection, universal connectors, and Guardium Data Security Center reports.
 *
 * OpenAPI spec version: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Reportsv3FieldName } from '../models/Reportsv3FieldName';
import { Reportsv3HeaderDescription } from '../models/Reportsv3HeaderDescription';
import { HttpFile } from '../http/http';

/**
* DisplayHeader that have the header name and the translated value.
*/
export class Reportsv3DisplayHeader {
    'fieldName'?: Reportsv3FieldName;
    'headerDescription'?: Reportsv3HeaderDescription;
    /**
    * The header ID.
    */
    'headerId'?: string;
    /**
    * The header name.
    */
    'headerName'?: string;
    /**
    * Sequence of the corresponding header.
    */
    'sequence'?: number;
    /**
    * Table name.
    */
    'tableName'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "fieldName",
            "baseName": "field_name",
            "type": "Reportsv3FieldName",
            "format": ""
        },
        {
            "name": "headerDescription",
            "baseName": "header_description",
            "type": "Reportsv3HeaderDescription",
            "format": ""
        },
        {
            "name": "headerId",
            "baseName": "header_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "headerName",
            "baseName": "header_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "sequence",
            "baseName": "sequence",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "tableName",
            "baseName": "table_name",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Reportsv3DisplayHeader.attributeTypeMap;
    }

    public constructor() {
    }
}

