/**
 * IBM Guardium Data Security Center
 * IBM Guardium Data Security Center simplifies your organization\'s Data Security architecture and enables access to long-term data security and compliance data. It provides security teams with risk-based views and alerts, as well as advanced analytics based on proprietary ML technology to uncover hidden threats. IBM Guardium Data Security Center gives security professionals the ability to quickly create data security and audit reports, monitor activity in on-prem and DBaaS sources, and take action from a central location.
 *
 * OpenAPI spec version: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Reportsv3DateRangeType } from '../models/Reportsv3DateRangeType';
import { Reportsv3DateRangeUnit } from '../models/Reportsv3DateRangeUnit';
import { HttpFile } from '../http/http';

/**
* DateRange represents a date range type - from an enum and if its custom / relative - the start and the end date.
*/
export class Reportsv3DateRange {
    /**
    * If custom holds the date string.
    */
    'endDate'?: string;
    /**
    * If custom-relative -  holds the end number.
    */
    'endNumber'?: number;
    'endUnit'?: Reportsv3DateRangeUnit;
    /**
    * If custom holds the date string.
    */
    'startDate'?: string;
    /**
    * If custom-relative -  holds the start number.
    */
    'startNumber'?: number;
    'startUnit'?: Reportsv3DateRangeUnit;
    'type'?: Reportsv3DateRangeType;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "endDate",
            "baseName": "end_date",
            "type": "string",
            "format": ""
        },
        {
            "name": "endNumber",
            "baseName": "end_number",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "endUnit",
            "baseName": "end_unit",
            "type": "Reportsv3DateRangeUnit",
            "format": ""
        },
        {
            "name": "startDate",
            "baseName": "start_date",
            "type": "string",
            "format": ""
        },
        {
            "name": "startNumber",
            "baseName": "start_number",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "startUnit",
            "baseName": "start_unit",
            "type": "Reportsv3DateRangeUnit",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "Reportsv3DateRangeType",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Reportsv3DateRange.attributeTypeMap;
    }

    public constructor() {
    }
}



