/**
 * IBM Guardium Data Security Center
 * Use Guardium Data Security Center SDK (application programming interfaces) to interact with other applications, such as Guardium Data Protection, universal connectors, and Guardium Data Security Center reports.
 *
 * OpenAPI spec version: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Riskanalyticscontrollerv3FindingDetails } from '../models/Riskanalyticscontrollerv3FindingDetails';
import { Riskanalyticscontrollerv3FindingReferenceLink } from '../models/Riskanalyticscontrollerv3FindingReferenceLink';
import { HttpFile } from '../http/http';

/**
* Contains a list of examples, reference links, in a finding category. If outlier finding, it could be HIGH_VOLUME, ERROR, NEW, and so on.
*/
export class Riskanalyticscontrollerv3FindingDetailsMap {
    'findingDetails'?: Riskanalyticscontrollerv3FindingDetails;
    'findingDetailsType'?: string;
    'findingReference'?: Riskanalyticscontrollerv3FindingReferenceLink;
    'report'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "findingDetails",
            "baseName": "finding_details",
            "type": "Riskanalyticscontrollerv3FindingDetails",
            "format": ""
        },
        {
            "name": "findingDetailsType",
            "baseName": "finding_details_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "findingReference",
            "baseName": "finding_reference",
            "type": "Riskanalyticscontrollerv3FindingReferenceLink",
            "format": ""
        },
        {
            "name": "report",
            "baseName": "report",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Riskanalyticscontrollerv3FindingDetailsMap.attributeTypeMap;
    }

    public constructor() {
    }
}
