/**
 * IBM Guardium Data Security Center
 * Use Guardium Data Security Center SDK (application programming interfaces) to interact with other applications, such as Guardium Data Protection, universal connectors, and Guardium Data Security Center reports.
 *
 * OpenAPI spec version: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Riskanalyticsdataprocessorv3Question } from '../models/Riskanalyticsdataprocessorv3Question';
import { HttpFile } from '../http/http';

/**
* GetRiskPredefinedQuestionsResponse message for the GetRiskPredefinedQuestions api.
*/
export class Riskanalyticsdataprocessorv3GetRiskPredefinedQuestionsResponse {
    'questions'?: Array<Riskanalyticsdataprocessorv3Question>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "questions",
            "baseName": "questions",
            "type": "Array<Riskanalyticsdataprocessorv3Question>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Riskanalyticsdataprocessorv3GetRiskPredefinedQuestionsResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
