/**
 * IBM Guardium Data Security Center
 * Use Guardium Data Security Center SDK (application programming interfaces) to interact with other applications, such as Guardium Data Protection, universal connectors, and Guardium Data Security Center reports.
 *
 * OpenAPI spec version: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Snifassistv3FeedbackStatus } from '../models/Snifassistv3FeedbackStatus';
import { HttpFile } from '../http/http';

/**
* Feedback defines the message structure for sniffer feedback.
*/
export class Snifassistv3Feedback {
    /**
    * Specify batch number uniquely associated with a policy or group update message.
    */
    'batchNum'?: string;
    /**
    * Description of the status.
    */
    'message'?: string;
    'status'?: Snifassistv3FeedbackStatus;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "batchNum",
            "baseName": "batch_num",
            "type": "string",
            "format": "int64"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "Snifassistv3FeedbackStatus",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Snifassistv3Feedback.attributeTypeMap;
    }

    public constructor() {
    }
}


