/**
 * IBM Guardium Data Security Center
 * Use Guardium Data Security Center SDK (application programming interfaces) to interact with other applications, such as Guardium Data Protection, universal connectors, and Guardium Data Security Center reports.
 *
 * OpenAPI spec version: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Tenantuserv3ExternalMetadata } from '../models/Tenantuserv3ExternalMetadata';
import { HttpFile } from '../http/http';

/**
* Tenant contains id, name, and settings for the specified tenant.
*/
export class Tenantuserv3Tenant {
    /**
    * Date tenant was activated.
    */
    'activationDate'?: Date;
    /**
    * Extrenal id.
    */
    'externalId'?: string;
    /**
    * External metadata.
    */
    'externalMetadata'?: { [key: string]: Tenantuserv3ExternalMetadata; };
    /**
    * Whether or not the tenant is disabled.
    */
    'isInactive'?: boolean;
    /**
    * Boolean is ready.
    */
    'isReady'?: boolean;
    'name'?: string;
    /**
    * Part number.
    */
    'partNumber'?: string;
    /**
    * Settings pertaining to all users of this tenant.
    */
    'settings'?: { [key: string]: string; };
    'status'?: string;
    'tenantCapabilities'?: { [key: string]: boolean; };
    /**
    * The unique id for the tenant object.
    */
    'tenantId'?: string;
    /**
    * Email.
    */
    'uid'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "activationDate",
            "baseName": "activation_date",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "externalId",
            "baseName": "external_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "externalMetadata",
            "baseName": "external_metadata",
            "type": "{ [key: string]: Tenantuserv3ExternalMetadata; }",
            "format": ""
        },
        {
            "name": "isInactive",
            "baseName": "is_inactive",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isReady",
            "baseName": "is_ready",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "partNumber",
            "baseName": "part_number",
            "type": "string",
            "format": ""
        },
        {
            "name": "settings",
            "baseName": "settings",
            "type": "{ [key: string]: string; }",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string",
            "format": ""
        },
        {
            "name": "tenantCapabilities",
            "baseName": "tenant_capabilities",
            "type": "{ [key: string]: boolean; }",
            "format": ""
        },
        {
            "name": "tenantId",
            "baseName": "tenant_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "uid",
            "baseName": "uid",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Tenantuserv3Tenant.attributeTypeMap;
    }

    public constructor() {
    }
}
