/**
 * IBM Guardium Data Security Center
 * Use Guardium Data Security Center SDK (application programming interfaces) to interact with other applications, such as Guardium Data Protection, universal connectors, and Guardium Data Security Center reports.
 *
 * OpenAPI spec version: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Vulmanagementv3SubCategory } from '../models/Vulmanagementv3SubCategory';
import { HttpFile } from '../http/http';

/**
* Category - Main Category Data for Manage Vulnerabilities Filter Panel.
*/
export class Vulmanagementv3Category {
    /**
    * Group - Tags.
    */
    'group'?: string;
    /**
    * Category ID.
    */
    'id'?: string;
    /**
    * Category Name.
    */
    'name'?: string;
    /**
    * List of sub categories.
    */
    'subCategory'?: Array<Vulmanagementv3SubCategory>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "group",
            "baseName": "group",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "subCategory",
            "baseName": "sub_category",
            "type": "Array<Vulmanagementv3SubCategory>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Vulmanagementv3Category.attributeTypeMap;
    }

    public constructor() {
    }
}
