/**
 * IBM Guardium Data Security Center
 * IBM Guardium Data Security Center simplifies your organization\'s Data Security architecture and enables access to long-term data security and compliance data. It provides security teams with risk-based views and alerts, as well as advanced analytics based on proprietary ML technology to uncover hidden threats. IBM Guardium Data Security Center gives security professionals the ability to quickly create data security and audit reports, monitor activity in on-prem and DBaaS sources, and take action from a central location.
 *
 * OpenAPI spec version: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VulnerabilitiesCriticalityCountInner } from '../models/VulnerabilitiesCriticalityCountInner';
import { VulnerabilitiesSummaryAffectedDataStoreSummary } from '../models/VulnerabilitiesSummaryAffectedDataStoreSummary';
import { VulnerabilitiesSummaryStatusSummary } from '../models/VulnerabilitiesSummaryStatusSummary';
import { VulnerabilitiesSummaryStatusTypeCountInner } from '../models/VulnerabilitiesSummaryStatusTypeCountInner';
import { VulnerabilitiesSummaryVulnerabilityTypeCountInner } from '../models/VulnerabilitiesSummaryVulnerabilityTypeCountInner';
import { HttpFile } from '../http/http';

export class VulnerabilitiesSummary {
    'criticalityCount': Array<VulnerabilitiesCriticalityCountInner>;
    'vulnerabilityTypeCount': Array<VulnerabilitiesSummaryVulnerabilityTypeCountInner>;
    'statusTypeCount': Array<VulnerabilitiesSummaryStatusTypeCountInner>;
    'statusSummary': VulnerabilitiesSummaryStatusSummary;
    'affectedDataStoreSummary': VulnerabilitiesSummaryAffectedDataStoreSummary;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "criticalityCount",
            "baseName": "criticalityCount",
            "type": "Array<VulnerabilitiesCriticalityCountInner>",
            "format": ""
        },
        {
            "name": "vulnerabilityTypeCount",
            "baseName": "vulnerabilityTypeCount",
            "type": "Array<VulnerabilitiesSummaryVulnerabilityTypeCountInner>",
            "format": ""
        },
        {
            "name": "statusTypeCount",
            "baseName": "statusTypeCount",
            "type": "Array<VulnerabilitiesSummaryStatusTypeCountInner>",
            "format": ""
        },
        {
            "name": "statusSummary",
            "baseName": "statusSummary",
            "type": "VulnerabilitiesSummaryStatusSummary",
            "format": ""
        },
        {
            "name": "affectedDataStoreSummary",
            "baseName": "affectedDataStoreSummary",
            "type": "VulnerabilitiesSummaryAffectedDataStoreSummary",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return VulnerabilitiesSummary.attributeTypeMap;
    }

    public constructor() {
    }
}

