/**
 * IBM Guardium Data Security Center
 * Use Guardium Data Security Center SDK (application programming interfaces) to interact with other applications, such as Guardium Data Protection, universal connectors, and Guardium Data Security Center reports.
 *
 * OpenAPI spec version: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Workflowv3Filter } from '../models/Workflowv3Filter';
import { HttpFile } from '../http/http';

/**
* Requests task count.
*/
export class Workflowv3GetTasksCountRequest {
    'caseId'?: string;
    'filter'?: Workflowv3Filter;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "caseId",
            "baseName": "case_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "filter",
            "baseName": "filter",
            "type": "Workflowv3Filter",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Workflowv3GetTasksCountRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

