/**
 * IBM Guardium Data Security Center
 * Use Guardium Data Security Center SDK (application programming interfaces) to interact with other applications, such as Guardium Data Protection, universal connectors, and Guardium Data Security Center reports.
 *
 * OpenAPI spec version: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GooglerpcStatus } from '../models/GooglerpcStatus';
import { Workflowv3Case } from '../models/Workflowv3Case';
import { Workflowv3Filter } from '../models/Workflowv3Filter';
import { HttpFile } from '../http/http';

/**
* Returns just cases with associated tasks.
*/
export class Workflowv3CaseListResponse {
    /**
    * Filtered list of cases.
    */
    'cases'?: Array<Workflowv3Case>;
    'filter'?: Workflowv3Filter;
    'status'?: GooglerpcStatus;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "cases",
            "baseName": "cases",
            "type": "Array<Workflowv3Case>",
            "format": ""
        },
        {
            "name": "filter",
            "baseName": "filter",
            "type": "Workflowv3Filter",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "GooglerpcStatus",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Workflowv3CaseListResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

