/**
 * IBM Guardium Data Security Center
 * Use Guardium Data Security Center SDK (application programming interfaces) to interact with other applications, such as Guardium Data Protection, universal connectors, and Guardium Data Security Center reports.
 *
 * OpenAPI spec version: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Workflowv3EntityType } from '../models/Workflowv3EntityType';
import { HttpFile } from '../http/http';

/**
* Case or task assignment entity.
*/
export class Workflowv3Entity {
    /**
    * Label of entity,  i.e. test@ibm.com.
    */
    'label'?: string;
    /**
    * Template for sending e-mail.
    */
    'templateId'?: string;
    'type'?: Workflowv3EntityType;
    /**
    * Value of entity, i.e. an e-mail address.
    */
    'value'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "label",
            "baseName": "label",
            "type": "string",
            "format": ""
        },
        {
            "name": "templateId",
            "baseName": "template_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "Workflowv3EntityType",
            "format": ""
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Workflowv3Entity.attributeTypeMap;
    }

    public constructor() {
    }
}


