/*
 * IBM Guardium Data Security Center
 *
 * IBM Guardium Data Security Center simplifies your organization's Data Security architecture and enables access to long-term data security and compliance data. It provides security teams with risk-based views and alerts, as well as advanced analytics based on proprietary ML technology to uncover hidden threats. IBM Guardium Data Security Center gives security professionals the ability to quickly create data security and audit reports, monitor activity in on-prem and DBaaS sources, and take action from a central location.
 *
 * API version: 3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// ClassificationMatchDetails contains the details about matched classifications.
type Riskanalyticsenginev3ClassificationMatchDetails struct {
	ClassKey string `json:"class_key,omitempty"`
	ClassValue float32 `json:"class_value,omitempty"`
	ClassificationConfidence float32 `json:"classification_confidence,omitempty"`
	ClassificationNls string `json:"classification_nls,omitempty"`
	ModelProbability float32 `json:"model_probability,omitempty"`
}
