/*
 * IBM Guardium Data Security Center
 *
 * IBM Guardium Data Security Center simplifies your organization's Data Security architecture and enables access to long-term data security and compliance data. It provides security teams with risk-based views and alerts, as well as advanced analytics based on proprietary ML technology to uncover hidden threats. IBM Guardium Data Security Center gives security professionals the ability to quickly create data security and audit reports, monitor activity in on-prem and DBaaS sources, and take action from a central location.
 *
 * API version: 3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Resourcecontrollerk8v3ControllerApp struct {
	Container *Resourcecontrollerk8v3Container `json:"container,omitempty"`
	Deployment *Resourcecontrollerk8v3AppDeployment `json:"deployment,omitempty"`
	EmptyDir string `json:"empty_dir,omitempty"`
	Files []Resourcecontrollerk8v3ControllerAppFile `json:"files,omitempty"`
	Hpa *Resourcecontrollerk8v3AppHpa `json:"hpa,omitempty"`
	// The internal ID of the app.
	Id string `json:"id,omitempty"`
	InitContainers []Resourcecontrollerk8v3InitContainer `json:"init_containers,omitempty"`
	// The date this app was modified (ms since epoch).
	Modified string `json:"modified,omitempty"`
	// The name of the app.
	Name string `json:"name,omitempty"`
	SecretKey string `json:"secret_key,omitempty"`
	Secrets []Resourcecontrollerk8v3ControllerAppSecret `json:"secrets,omitempty"`
}
