/*
 * IBM Guardium Data Security Center
 *
 * IBM Guardium Data Security Center simplifies your organization's Data Security architecture and enables access to long-term data security and compliance data. It provides security teams with risk-based views and alerts, as well as advanced analytics based on proprietary ML technology to uncover hidden threats. IBM Guardium Data Security Center gives security professionals the ability to quickly create data security and audit reports, monitor activity in on-prem and DBaaS sources, and take action from a central location.
 *
 * API version: 3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// S-tap related information object.
type Healthcollectorv3StapInformationObject struct {
	// Details of inspection engines present at start and end.
	InspectionEngineDetails []Healthcollectorv3InspectionEnginePresentDetails `json:"inspection_engine_details,omitempty"`
	// Difference of inspection engines present at start and end.
	InspectionEngineDetailsChange int32 `json:"inspection_engine_details_change,omitempty"`
	// Indicates whether the s-tap was present at end.
	PresentAtEnd bool `json:"present_at_end,omitempty"`
	// Indicates whether the s-tap was present at start.
	PresentAtStart bool `json:"present_at_start,omitempty"`
	Stap *Healthcollectorv3StapObject `json:"stap,omitempty"`
}
