/*
 * IBM Guardium Data Security Center
 *
 * IBM Guardium Data Security Center simplifies your organization's Data Security architecture and enables access to long-term data security and compliance data. It provides security teams with risk-based views and alerts, as well as advanced analytics based on proprietary ML technology to uncover hidden threats. IBM Guardium Data Security Center gives security professionals the ability to quickly create data security and audit reports, monitor activity in on-prem and DBaaS sources, and take action from a central location.
 *
 * API version: 3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
// Schedulerv3Month : Month is the month of the year.
type Schedulerv3Month string

// List of schedulerv3Month
const (
	EVERYMONTH_Schedulerv3Month Schedulerv3Month = "EVERYMONTH"
	JANUARY_Schedulerv3Month Schedulerv3Month = "JANUARY"
	FEBRUARY_Schedulerv3Month Schedulerv3Month = "FEBRUARY"
	MARCH_Schedulerv3Month Schedulerv3Month = "MARCH"
	APRIL_Schedulerv3Month Schedulerv3Month = "APRIL"
	MAY_Schedulerv3Month Schedulerv3Month = "MAY"
	JUNE_Schedulerv3Month Schedulerv3Month = "JUNE"
	JULY_Schedulerv3Month Schedulerv3Month = "JULY"
	AUGUST_Schedulerv3Month Schedulerv3Month = "AUGUST"
	SEPTEMBER_Schedulerv3Month Schedulerv3Month = "SEPTEMBER"
	OCTOBER_Schedulerv3Month Schedulerv3Month = "OCTOBER"
	NOVEMBER_Schedulerv3Month Schedulerv3Month = "NOVEMBER"
	DECEMBER_Schedulerv3Month Schedulerv3Month = "DECEMBER"
)
