/*
 * IBM Guardium Data Security Center
 *
 * IBM Guardium Data Security Center simplifies your organization's Data Security architecture and enables access to long-term data security and compliance data. It provides security teams with risk-based views and alerts, as well as advanced analytics based on proprietary ML technology to uncover hidden threats. IBM Guardium Data Security Center gives security professionals the ability to quickly create data security and audit reports, monitor activity in on-prem and DBaaS sources, and take action from a central location.
 *
 * API version: 3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

// An activity log record indicates who, what, when, where, and why something happened.  For the purposes of this service: who   = The unique user ID for the user that performed the operation. what  = The operation performed (CRUD operation or other action taken). when  = The time the operation, request, or event occurred. where = The context in which the operation was performed. why   = Details about the operation being performed. which = The unique service record id for the service that recorded the event. actor = When available track the actor that performed the activity.
type Auditv3ActivityRecord struct {
	// The operation peformed (CRUD or other operation) (what).
	ActionTaken string `json:"action_taken,omitempty"`
	// Further info about the request (why).
	ChangesMade string `json:"changes_made,omitempty"`
	// The entity (collection name) upon which the operation was performed (where).
	Context string `json:"context,omitempty"`
	// Contains a brief description of the Activity record.
	ContextDescription string `json:"context_description,omitempty"`
	// The time the Activity record was created (when).
	CreationTime time.Time `json:"creation_time,omitempty"`
	// UserID if the request originated from an external context (who).
	PerformedBy string `json:"performed_by,omitempty"`
	// The record ID that the operation was performed upon (which).
	Uid string `json:"uid,omitempty"`
}
