/*
 * IBM Guardium Data Security Center
 *
 * IBM Guardium Data Security Center simplifies your organization's Data Security architecture and enables access to long-term data security and compliance data. It provides security teams with risk-based views and alerts, as well as advanced analytics based on proprietary ML technology to uncover hidden threats. IBM Guardium Data Security Center gives security professionals the ability to quickly create data security and audit reports, monitor activity in on-prem and DBaaS sources, and take action from a central location.
 *
 * API version: 3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Base oauth client object which is used in get and list APIs.
type AuthserverOauthClient struct {
	// ClientID of registered OAuth.
	ClientId string `json:"client_id,omitempty"`
	// ClientSecret of registered OAuth.
	ClientSecret string `json:"client_secret,omitempty"`
	// Description of oauth client.
	Description string `json:"description,omitempty"`
	// Name of oauth client.
	Name string `json:"name,omitempty"`
}
