/*
 * IBM Guardium Data Security Center
 *
 * IBM Guardium Data Security Center simplifies your organization's Data Security architecture and enables access to long-term data security and compliance data. It provides security teams with risk-based views and alerts, as well as advanced analytics based on proprietary ML technology to uncover hidden threats. IBM Guardium Data Security Center gives security professionals the ability to quickly create data security and audit reports, monitor activity in on-prem and DBaaS sources, and take action from a central location.
 *
 * API version: 3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Action metadata object.
type Policybuilderv3ActionMetadata struct {
	// Name of the action.
	ActionName string `json:"action_name,omitempty"`
	// Ui label for the action.
	Label string `json:"label,omitempty"`
	// Action parameters.
	Parameters []Policybuilderv3ActionParameterMetadata `json:"parameters,omitempty"`
	// Rule type for the action.
	RuleType []Policybuilderv3RuleType `json:"rule_type,omitempty"`
	Type_ *Policybuilderv3ActionType `json:"type,omitempty"`
}
