/*
 * IBM Guardium Data Security Center
 *
 * IBM Guardium Data Security Center simplifies your organization's Data Security architecture and enables access to long-term data security and compliance data. It provides security teams with risk-based views and alerts, as well as advanced analytics based on proprietary ML technology to uncover hidden threats. IBM Guardium Data Security Center gives security professionals the ability to quickly create data security and audit reports, monitor activity in on-prem and DBaaS sources, and take action from a central location.
 *
 * API version: 3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Job contains the information about a job.
type Resourcecontrollerk8v3Job struct {
	ClusterRoleRules []Resourcecontrollerk8v3Rule `json:"cluster_role_rules,omitempty"`
	// Optional:  The optional command to execute as part of the job (if the container entrypoint is insufficient).
	Command []string `json:"command,omitempty"`
	Container *Resourcecontrollerk8v3Container `json:"container,omitempty"`
	// The ID of the controller to execute the job on.
	ControllerId string `json:"controller_id,omitempty"`
	// Optional:  The date this job was created (ms since epoch).
	Created string `json:"created,omitempty"`
	Cron *Resourcecontrollerk8v3Cron `json:"cron,omitempty"`
	// Optional:  The files for the job.
	Files []Resourcecontrollerk8v3File `json:"files,omitempty"`
	// The ID of the job.
	Id string `json:"id,omitempty"`
	// Optional:  The labels for the associated job, cron job, and pod.
	Labels map[string]string `json:"labels,omitempty"`
	LastExecution *Resourcecontrollerk8v3JobExecution `json:"last_execution,omitempty"`
	// Optional:  The date this job was modified (ms since epoch).
	Modified string `json:"modified,omitempty"`
	// The name of the job.
	Name string `json:"name,omitempty"`
	RoleRules []Resourcecontrollerk8v3Rule `json:"role_rules,omitempty"`
	SecretKey string `json:"secret_key,omitempty"`
	// Optional:  The secrets for the job.
	Secrets []Resourcecontrollerk8v3Secret `json:"secrets,omitempty"`
	// Optional:  The current job status.
	Status string `json:"status,omitempty"`
}
