/*
 * IBM Guardium Data Security Center
 *
 * IBM Guardium Data Security Center simplifies your organization's Data Security architecture and enables access to long-term data security and compliance data. It provides security teams with risk-based views and alerts, as well as advanced analytics based on proprietary ML technology to uncover hidden threats. IBM Guardium Data Security Center gives security professionals the ability to quickly create data security and audit reports, monitor activity in on-prem and DBaaS sources, and take action from a central location.
 *
 * API version: 3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

// Datasource Definition encapsulates all data necessary for a handling datasource in Universal Connector.
type Universalconnectormanagerv3DatasourceDefinition struct {
	// Datasource configuration filter section text.
	DatasourceFilter string `json:"datasource_filter,omitempty"`
	// The datasource ID.
	DatasourceId string `json:"datasource_id,omitempty"`
	// Datasource configuration input section text.
	DatasourceInput string `json:"datasource_input,omitempty"`
	// Datasource name.
	DatasourceName string `json:"datasource_name,omitempty"`
	// The name of the user created datasource.
	OwnerUserId string `json:"owner_user_id,omitempty"`
	// The datasource update time.
	UpdateTime time.Time `json:"update_time,omitempty"`
}
