/*
 * IBM Guardium Data Security Center
 *
 * IBM Guardium Data Security Center simplifies your organization's Data Security architecture and enables access to long-term data security and compliance data. It provides security teams with risk-based views and alerts, as well as advanced analytics based on proprietary ML technology to uncover hidden threats. IBM Guardium Data Security Center gives security professionals the ability to quickly create data security and audit reports, monitor activity in on-prem and DBaaS sources, and take action from a central location.
 *
 * API version: 3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Information about monitoring agents.
type Guardiumconnectorv3StapObject struct {
	// Host name of Guardium Data Protection system.
	CollectorHostname string `json:"collector_hostname,omitempty"`
	// Connectivity status.
	Connectivity int32 `json:"connectivity,omitempty"`
	Details *Guardiumconnectorv3StapDetailsObject `json:"details,omitempty"`
	// Overall status of inspection engines.
	IeStatus int32 `json:"ieStatus,omitempty"`
	// List of inspection engines.
	IeList []Guardiumconnectorv3InspectionEngineObject `json:"ie_list,omitempty"`
	// Count of inspection engines.
	Inspectionengine int32 `json:"inspectionengine,omitempty"`
	// K-TAP status.
	Ktap int32 `json:"ktap,omitempty"`
	// Name of the S-TAP.
	Name string `json:"name,omitempty"`
	// Operating system.
	OsType string `json:"os_type,omitempty"`
	// Revision.
	Revision string `json:"revision,omitempty"`
	// IP address.
	StapIp string `json:"stap_ip,omitempty"`
	// Overall status.
	Status int32 `json:"status,omitempty"`
	// Traffic status.
	Traffic int32 `json:"traffic,omitempty"`
}
