/*
 * IBM Guardium Data Security Center
 *
 * IBM Guardium Data Security Center simplifies your organization's Data Security architecture and enables access to long-term data security and compliance data. It provides security teams with risk-based views and alerts, as well as advanced analytics based on proprietary ML technology to uncover hidden threats. IBM Guardium Data Security Center gives security professionals the ability to quickly create data security and audit reports, monitor activity in on-prem and DBaaS sources, and take action from a central location.
 *
 * API version: 3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

// Group imports groups from a Guradium Data Protection central manager to Guardium Insights.
type Groupbuilderv3Group struct {
	// Group access level.
	AccessLevel int32 `json:"access_level,omitempty"`
	// Group description.
	Description string `json:"description,omitempty"`
	// Flattened member count for nested groups.
	FlattenedMemberCount int32 `json:"flattened_member_count,omitempty"`
	// Group ID.
	GroupId int32 `json:"group_id,omitempty"`
	// Group type ID.
	GroupTypeId int32 `json:"group_type_id,omitempty"`
	// Last synchronization date.
	LastSyncDate time.Time `json:"last_sync_date,omitempty"`
	LdapConfig *Groupbuilderv3LdapConfig `json:"ldap_config,omitempty"`
	// Group members count.
	MemberCount int32 `json:"member_count,omitempty"`
	// Array of members.
	Members []Groupbuilderv3GroupMember `json:"members,omitempty"`
	// Group name.
	Name string `json:"name,omitempty"`
	// Nested (hierarchical).
	Nested bool `json:"nested,omitempty"`
	// Array of nested (hierarchical) members.
	NestedGroupMembers []Groupbuilderv3NestedGroupMember `json:"nested_group_members,omitempty"`
	// Next synchronization date.
	NextSyncDate time.Time `json:"next_sync_date,omitempty"`
	// Synchronization inactive code.
	SyncInactiveCode int32 `json:"sync_inactive_code,omitempty"`
	// Name of Guardium Data Protection central manager synchronized to the group.
	SyncSource string `json:"sync_source,omitempty"`
	// Synchronized.
	Synced bool `json:"synced,omitempty"`
	// Group tuples count.
	TupleCount int32 `json:"tuple_count,omitempty"`
	// Tuple parameters.
	TupleParams []string `json:"tuple_params,omitempty"`
}
