/*
 * IBM Guardium Data Security Center
 *
 * IBM Guardium Data Security Center simplifies your organization's Data Security architecture and enables access to long-term data security and compliance data. It provides security teams with risk-based views and alerts, as well as advanced analytics based on proprietary ML technology to uncover hidden threats. IBM Guardium Data Security Center gives security professionals the ability to quickly create data security and audit reports, monitor activity in on-prem and DBaaS sources, and take action from a central location.
 *
 * API version: 3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
// Assetsv3HealthType : HealthType : Assets Health types.   - UNSPECIFIED: Unspecified Health types.  - HEALTHY: Healthy Health types.  - UNKNOWN: Unknown Health types.  - UNHEALTHY_MINOR: Unhealthy Minor Health types.  - UNHEALTHY_MAJOR: Unhealthy major Health types.
type Assetsv3HealthType string

// List of assetsv3HealthType
const (
	UNSPECIFIED_Assetsv3HealthType Assetsv3HealthType = "UNSPECIFIED"
	HEALTHY_Assetsv3HealthType Assetsv3HealthType = "HEALTHY"
	UNKNOWN_Assetsv3HealthType Assetsv3HealthType = "UNKNOWN"
	UNHEALTHY_MINOR_Assetsv3HealthType Assetsv3HealthType = "UNHEALTHY_MINOR"
	UNHEALTHY_MAJOR_Assetsv3HealthType Assetsv3HealthType = "UNHEALTHY_MAJOR"
)
