/*
 * IBM Guardium Data Security Center
 *
 * IBM Guardium Data Security Center simplifies your organization's Data Security architecture and enables access to long-term data security and compliance data. It provides security teams with risk-based views and alerts, as well as advanced analytics based on proprietary ML technology to uncover hidden threats. IBM Guardium Data Security Center gives security professionals the ability to quickly create data security and audit reports, monitor activity in on-prem and DBaaS sources, and take action from a central location.
 *
 * API version: 3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Assetsv3DeploymentVertex struct {
	City string `json:"city,omitempty"`
	Country string `json:"country,omitempty"`
	Criticality *Assetsv3Level `json:"criticality,omitempty"`
	DataCenter string `json:"data_center,omitempty"`
	DeploymentAccount []Assetsv3ConnectionEdge `json:"deployment_account,omitempty"`
	DeploymentId string `json:"deployment_id,omitempty"`
	DeploymentSubscription []Assetsv3ConnectionEdge `json:"deployment_subscription,omitempty"`
	Dns string `json:"dns,omitempty"`
	Environment string `json:"environment,omitempty"`
	ExtendedProperties []Assetsv3CustomProperty `json:"extended_properties,omitempty"`
	Name string `json:"name,omitempty"`
	Region string `json:"region,omitempty"`
	ResolutionKey string `json:"resolution_key,omitempty"`
	RiskLevel *Assetsv3Level `json:"risk_level,omitempty"`
	Service string `json:"service,omitempty"`
	State string `json:"state,omitempty"`
	Type_ string `json:"type,omitempty"`
}
