/*
 * IBM Guardium Data Security Center
 * Use Guardium Data Security Center SDK (application programming interfaces) to interact with other applications, such as Guardium Data Protection, universal connectors, and Guardium Data Security Center reports.
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ibm.security.guardium;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Groupbuilderv3GetGroupsResponseGdp
 */
public class Groupbuilderv3GetGroupsResponseGdpTest {
    private final Groupbuilderv3GetGroupsResponseGdp model = new Groupbuilderv3GetGroupsResponseGdp();

    /**
     * Model tests for Groupbuilderv3GetGroupsResponseGdp
     */
    @Test
    public void testGroupbuilderv3GetGroupsResponseGdp() {
        // TODO: test Groupbuilderv3GetGroupsResponseGdp
    }

    /**
     * Test the property 'response'
     */
    @Test
    public void responseTest() {
        // TODO: test response
    }

    /**
     * Test the property 'responseCode'
     */
    @Test
    public void responseCodeTest() {
        // TODO: test responseCode
    }

}
