/*
 * IBM Guardium Data Security Center
 * Use Guardium Data Security Center SDK (application programming interfaces) to interact with other applications, such as Guardium Data Protection, universal connectors, and Guardium Data Security Center reports.
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ibm.security.guardium;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.ibm.security.guardium.Guardiumconnectorv3StatusResponseBase;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Guardiumconnectorv3ConfigureAggregatorExportResponse
 */
public class Guardiumconnectorv3ConfigureAggregatorExportResponseTest {
    private final Guardiumconnectorv3ConfigureAggregatorExportResponse model = new Guardiumconnectorv3ConfigureAggregatorExportResponse();

    /**
     * Model tests for Guardiumconnectorv3ConfigureAggregatorExportResponse
     */
    @Test
    public void testGuardiumconnectorv3ConfigureAggregatorExportResponse() {
        // TODO: test Guardiumconnectorv3ConfigureAggregatorExportResponse
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

}
