/*
 * IBM Guardium Data Security Center
 * Use Guardium Data Security Center SDK (application programming interfaces) to interact with other applications, such as Guardium Data Protection, universal connectors, and Guardium Data Security Center reports.
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ibm.security.guardium;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.ibm.security.guardium.SensitivitySummary;
import com.ibm.security.guardium.Vendor;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for LinkedVendor
 */
public class LinkedVendorTest {
    private final LinkedVendor model = new LinkedVendor();

    /**
     * Model tests for LinkedVendor
     */
    @Test
    public void testLinkedVendor() {
        // TODO: test LinkedVendor
    }

    /**
     * Test the property 'vendor'
     */
    @Test
    public void vendorTest() {
        // TODO: test vendor
    }

    /**
     * Test the property 'totalAccounts'
     */
    @Test
    public void totalAccountsTest() {
        // TODO: test totalAccounts
    }

    /**
     * Test the property 'isSensitive'
     */
    @Test
    public void isSensitiveTest() {
        // TODO: test isSensitive
    }

    /**
     * Test the property 'sensitivitySummary'
     */
    @Test
    public void sensitivitySummaryTest() {
        // TODO: test sensitivitySummary
    }

}
