/*
 * IBM Guardium Data Security Center
 * Use Guardium Data Security Center SDK (application programming interfaces) to interact with other applications, such as Guardium Data Protection, universal connectors, and Guardium Data Security Center reports.
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ibm.security.guardium;

import com.ibm.security.ApiException;
import com.ibm.security.guardium.Riskanalyticsmlclassificationv3ResetModelToDefaultsResponse;
import com.ibm.security.guardium.RuntimeError;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for RiskAnalyticsMlClassificationApi
 */
@Disabled
public class RiskAnalyticsMlClassificationApiTest {

    private final RiskAnalyticsMlClassificationApi api = new RiskAnalyticsMlClassificationApi();

    /**
     * Summary: Reset the model to its default weights. Description: Load the initial model instead of the existing model - this action is irreversible.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void riskAnalyticsMlClassificationResetModelToDefaultsTest() throws ApiException {
        Riskanalyticsmlclassificationv3ResetModelToDefaultsResponse response = api.riskAnalyticsMlClassificationResetModelToDefaults();
        // TODO: test validations
    }

}
