/*
 * IBM Guardium Data Security Center
 * Use Guardium Data Security Center SDK (application programming interfaces) to interact with other applications, such as Guardium Data Protection, universal connectors, and Guardium Data Security Center reports.
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ibm.security.guardium;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Tenantuserv3PostUsersBulkResponse
 */
public class Tenantuserv3PostUsersBulkResponseTest {
    private final Tenantuserv3PostUsersBulkResponse model = new Tenantuserv3PostUsersBulkResponse();

    /**
     * Model tests for Tenantuserv3PostUsersBulkResponse
     */
    @Test
    public void testTenantuserv3PostUsersBulkResponse() {
        // TODO: test Tenantuserv3PostUsersBulkResponse
    }

    /**
     * Test the property 'location'
     */
    @Test
    public void locationTest() {
        // TODO: test location
    }

    /**
     * Test the property 'userIds'
     */
    @Test
    public void userIdsTest() {
        // TODO: test userIds
    }

}
