/*
 * IBM Guardium Data Security Center
 * Use Guardium Data Security Center SDK (application programming interfaces) to interact with other applications, such as Guardium Data Protection, universal connectors, and Guardium Data Security Center reports.
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ibm.security.guardium;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.ibm.security.guardium.Vulmanagementv3Category;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Vulmanagementv3GetFiltersDataResponse
 */
public class Vulmanagementv3GetFiltersDataResponseTest {
    private final Vulmanagementv3GetFiltersDataResponse model = new Vulmanagementv3GetFiltersDataResponse();

    /**
     * Model tests for Vulmanagementv3GetFiltersDataResponse
     */
    @Test
    public void testVulmanagementv3GetFiltersDataResponse() {
        // TODO: test Vulmanagementv3GetFiltersDataResponse
    }

    /**
     * Test the property 'category'
     */
    @Test
    public void categoryTest() {
        // TODO: test category
    }

}
