/*
 * IBM Guardium Data Security Center
 * Use Guardium Data Security Center SDK (application programming interfaces) to interact with other applications, such as Guardium Data Protection, universal connectors, and Guardium Data Security Center reports.
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ibm.security.guardium;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.ibm.security.guardium.Reportsv3ReportFilterBrackets;
import com.ibm.security.guardium.Schedulerv3TaskType;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Workflowv3ReportRun
 */
public class Workflowv3ReportRunTest {
    private final Workflowv3ReportRun model = new Workflowv3ReportRun();

    /**
     * Model tests for Workflowv3ReportRun
     */
    @Test
    public void testWorkflowv3ReportRun() {
        // TODO: test Workflowv3ReportRun
    }

    /**
     * Test the property 'dateEnd'
     */
    @Test
    public void dateEndTest() {
        // TODO: test dateEnd
    }

    /**
     * Test the property 'dateStart'
     */
    @Test
    public void dateStartTest() {
        // TODO: test dateStart
    }

    /**
     * Test the property 'detail'
     */
    @Test
    public void detailTest() {
        // TODO: test detail
    }

    /**
     * Test the property 'queryFrom'
     */
    @Test
    public void queryFromTest() {
        // TODO: test queryFrom
    }

    /**
     * Test the property 'queryTo'
     */
    @Test
    public void queryToTest() {
        // TODO: test queryTo
    }

    /**
     * Test the property 'reportFilters'
     */
    @Test
    public void reportFiltersTest() {
        // TODO: test reportFilters
    }

    /**
     * Test the property 'reportId'
     */
    @Test
    public void reportIdTest() {
        // TODO: test reportId
    }

    /**
     * Test the property 'reportName'
     */
    @Test
    public void reportNameTest() {
        // TODO: test reportName
    }

    /**
     * Test the property 'reportResultFileName'
     */
    @Test
    public void reportResultFileNameTest() {
        // TODO: test reportResultFileName
    }

    /**
     * Test the property 'runId'
     */
    @Test
    public void runIdTest() {
        // TODO: test runId
    }

    /**
     * Test the property 'scheduledJobId'
     */
    @Test
    public void scheduledJobIdTest() {
        // TODO: test scheduledJobId
    }

    /**
     * Test the property 'scheduledJobName'
     */
    @Test
    public void scheduledJobNameTest() {
        // TODO: test scheduledJobName
    }

    /**
     * Test the property 'scheduledTaskId'
     */
    @Test
    public void scheduledTaskIdTest() {
        // TODO: test scheduledTaskId
    }

    /**
     * Test the property 'scheduledTaskType'
     */
    @Test
    public void scheduledTaskTypeTest() {
        // TODO: test scheduledTaskType
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

}
