/*
 * IBM Guardium Data Security Center
 * IBM Guardium Data Security Center simplifies your organization's Data Security architecture and enables access to long-term data security and compliance data. It provides security teams with risk-based views and alerts, as well as advanced analytics based on proprietary ML technology to uncover hidden threats. IBM Guardium Data Security Center gives security professionals the ability to quickly create data security and audit reports, monitor activity in on-prem and DBaaS sources, and take action from a central location.
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Guardiumconnectorv3StapLiveInfoObject
 */
public class Guardiumconnectorv3StapLiveInfoObjectTest {
    private final Guardiumconnectorv3StapLiveInfoObject model = new Guardiumconnectorv3StapLiveInfoObject();

    /**
     * Model tests for Guardiumconnectorv3StapLiveInfoObject
     */
    @Test
    public void testGuardiumconnectorv3StapLiveInfoObject() {
        // TODO: test Guardiumconnectorv3StapLiveInfoObject
    }

    /**
     * Test the property 'hasEvent'
     */
    @Test
    public void hasEventTest() {
        // TODO: test hasEvent
    }

    /**
     * Test the property 'healthStatus'
     */
    @Test
    public void healthStatusTest() {
        // TODO: test healthStatus
    }

    /**
     * Test the property 'livelinessState'
     */
    @Test
    public void livelinessStateTest() {
        // TODO: test livelinessState
    }

    /**
     * Test the property 'stap'
     */
    @Test
    public void stapTest() {
        // TODO: test stap
    }

}
