/*
 * IBM Guardium Data Security Center
 * IBM Guardium Data Security Center simplifies your organization's Data Security architecture and enables access to long-term data security and compliance data. It provides security teams with risk-based views and alerts, as well as advanced analytics based on proprietary ML technology to uncover hidden threats. IBM Guardium Data Security Center gives security professionals the ability to quickly create data security and audit reports, monitor activity in on-prem and DBaaS sources, and take action from a central location.
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.Schedulerv3DayOfWeek;
import org.openapitools.client.model.Schedulerv3DayOrder;
import org.openapitools.client.model.Schedulerv3Frequency;
import org.openapitools.client.model.Schedulerv3Month;
import org.openapitools.client.model.Schedulerv3RepeatBegin;
import org.openapitools.client.model.Schedulerv3RepeatEnd;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Schedulerv3Scheduler
 */
public class Schedulerv3SchedulerTest {
    private final Schedulerv3Scheduler model = new Schedulerv3Scheduler();

    /**
     * Model tests for Schedulerv3Scheduler
     */
    @Test
    public void testSchedulerv3Scheduler() {
        // TODO: test Schedulerv3Scheduler
    }

    /**
     * Test the property 'beginSchedule'
     */
    @Test
    public void beginScheduleTest() {
        // TODO: test beginSchedule
    }

    /**
     * Test the property 'byDayOfMonth'
     */
    @Test
    public void byDayOfMonthTest() {
        // TODO: test byDayOfMonth
    }

    /**
     * Test the property 'dayOfMonth'
     */
    @Test
    public void dayOfMonthTest() {
        // TODO: test dayOfMonth
    }

    /**
     * Test the property 'dayOfWeek'
     */
    @Test
    public void dayOfWeekTest() {
        // TODO: test dayOfWeek
    }

    /**
     * Test the property 'dayOrder'
     */
    @Test
    public void dayOrderTest() {
        // TODO: test dayOrder
    }

    /**
     * Test the property 'dayOrderDayOfWeek'
     */
    @Test
    public void dayOrderDayOfWeekTest() {
        // TODO: test dayOrderDayOfWeek
    }

    /**
     * Test the property 'endSchedule'
     */
    @Test
    public void endScheduleTest() {
        // TODO: test endSchedule
    }

    /**
     * Test the property 'frequency'
     */
    @Test
    public void frequencyTest() {
        // TODO: test frequency
    }

    /**
     * Test the property 'months'
     */
    @Test
    public void monthsTest() {
        // TODO: test months
    }

    /**
     * Test the property 'neverEnd'
     */
    @Test
    public void neverEndTest() {
        // TODO: test neverEnd
    }

    /**
     * Test the property 'repeat'
     */
    @Test
    public void repeatTest() {
        // TODO: test repeat
    }

    /**
     * Test the property 'repeatBegin'
     */
    @Test
    public void repeatBeginTest() {
        // TODO: test repeatBegin
    }

    /**
     * Test the property 'repeatEnd'
     */
    @Test
    public void repeatEndTest() {
        // TODO: test repeatEnd
    }

    /**
     * Test the property 'repeatMinutes'
     */
    @Test
    public void repeatMinutesTest() {
        // TODO: test repeatMinutes
    }

    /**
     * Test the property 'runOnceNow'
     */
    @Test
    public void runOnceNowTest() {
        // TODO: test runOnceNow
    }

}
